name: tokamak       # names the results folder: letters, digits, _ and - only
pusher: boris          # boris | higuera_cary | vay
dt: 7.0e-13            # time step [s]
n_steps: 30         # number of time steps
save_every: 5          # keep one state every 5 steps (must divide n_steps)
seed: 42               # random seed (not used yet: needed once collisions exist)

q: -1.602176634e-19    # charge [C]: negative for an electron
m: 9.1093837139e-31    # mass [kg]

#config proposée dans l'article 
field:
  kind: tokamak
  b0: 5.3
  r0: 6.2
  lamb : 4
  q0 : 1.6
  b_r: "0"
  b_theta: "b0 * r * q0 * (1 + r**2/lamb**2) * 1 / r0*(1 + (r/r0)*cos(theta))"
  b_phi: "b0 * 1 / (1 + (r/r0)*cos(theta))"


initial:
  x0: [[0, 7.2, 0]]              # positions [m], one row [x, y, z] per particle
  u0: [[2.946e08, 5.205e7, 1.8604e07]]      # proper velocities u = gamma*v [m/s], one row per particle

